version: "3"

services:
  neo4j:
    image: neo4j:5.15-community-bullseye
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/var/lib/neo4j/data
    environment:
      - NEO4J_AUTH=none

  pgsql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
      POSTGRES_DB: user_data
    ports:
      - 5432:5432
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  weaviate:
    command:
      - --host
      - "0.0.0.0"
      - --port
      - "8888"
      - --scheme
      - http
    image: semitechnologies/weaviate:1.22.4
    ports:
      - 8888:8888
    volumes:
      - weaviate-data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: true
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_USERS: admin-rw,admin-ro
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: readwrite,readonly
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      CLUSTER_HOSTNAME: node1

  # localstack provides all AWS services except Cognito (requires paid version)
  localstack:
    image: localstack/localstack:3.0
    environment:
      SERVICES: s3,sqs,lambda
      EAGER_SERVICE_LOADING: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      # DEBUG: 1
    volumes:
      # https://docs.localstack.cloud/references/init-hooks/
      - ./scripts/localstack_onready.sh:/etc/localstack/init/ready.d/init-aws.sh
      # https://docs.localstack.cloud/references/filesystem/
      - localstack-data:/var/lib/localstack
    ports:
      - 4566:4566

  cognito:
    image: jagregory/cognito-local:3-latest
    volumes:
      - cognito-local-data:/app/.cognito
    ports:
      - 9229:9229

  sendgrid:
    image: ghashange/sendgrid-mock:1.9.0
    environment:
      - API_KEY=sendgridapikey
    ports:
      - 4321:3000

  ray-mocks:
    build:
      context: ../
      dockerfile: ./infra/http_servers/http_server.Dockerfile
    ports:
      - 8001:8080
    environment:
      SERVER_MODULE: ray_services_mock

volumes:
  pgsql-data:
  neo4j-data:
  weaviate-data:
  localstack-data:
  cognito-local-data:
